import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { CATEGORY_ICON_MAP, INTERFACE_ICONS } from './icons.manifest.ts';

// Writes src/generated/icons.tsx: one component per Remix Icon in the
// manifest, read from the pinned remixicon package, so unused icons never
// reach the bundle. `--check` fails when the file differs from what would
// be written.

const target = fileURLToPath(
  new URL('../src/generated/icons.tsx', import.meta.url),
);
const iconsDir = fileURLToPath(
  new URL('../node_modules/remixicon/icons/', import.meta.url),
);

export function iconNames(): string[] {
  return [
    ...new Set([...INTERFACE_ICONS, ...Object.values(CATEGORY_ICON_MAP)]),
  ].sort();
}

/** `bank-line` to `IconBankLine`. */
export function componentName(icon: string): string {
  return `Icon${icon
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')}`;
}

function findSvg(icon: string): string {
  for (const group of readdirSync(iconsDir, { withFileTypes: true })) {
    if (!group.isDirectory()) continue;
    try {
      return readFileSync(join(iconsDir, group.name, `${icon}.svg`), 'utf8');
    } catch {
      // Not in this group.
    }
  }
  throw new Error(`Remix icon "${icon}" not found in ${iconsDir}`);
}

/** The path data of an icon, without the empty 24 x 24 placeholder. */
export function pathsOf(svg: string): string[] {
  const paths = [...svg.matchAll(/<path\b[^>]*>/g)].flatMap(([tag]) => {
    if (/fill="none"/.test(tag)) return [];
    const d = /\bd="([^"]*)"/.exec(tag)?.[1];
    return d === undefined ? [] : [d];
  });
  if (paths.length === 0) throw new Error('Icon has no path data');
  return paths;
}

export function iconsTsx(read: (icon: string) => string = findSvg): string {
  const names = iconNames();
  const components = names.map((icon) => {
    const paths = pathsOf(read(icon))
      .map((d) => `    <path d="${d}" />`)
      .join('\n');
    return [
      `export function ${componentName(icon)}(props: IconProps) {`,
      '  return (',
      '    <svg {...base} {...props}>',
      paths.replace(/^ {2}/gm, '  '),
      '    </svg>',
      '  );',
      '}',
    ].join('\n');
  });
  const entries = Object.entries(CATEGORY_ICON_MAP).map(
    ([key, icon]) => `  '${key}': ${componentName(icon)},`,
  );
  return [
    '// Generated by scripts/generate-icons.ts. Do not edit.',
    '',
    "import type { CategoryIcon } from '@allotr/shared';",
    "import type { ComponentType, SVGProps } from 'react';",
    '',
    "export type IconProps = Omit<SVGProps<SVGSVGElement>, 'children'>;",
    '',
    'const base = {',
    "  viewBox: '0 0 24 24',",
    "  width: '1em',",
    "  height: '1em',",
    "  fill: 'currentColor',",
    "  'aria-hidden': true,",
    '  focusable: false,',
    '} as const;',
    '',
    components.join('\n\n'),
    '',
    'export const categoryIconComponents: Record<',
    '  CategoryIcon,',
    '  ComponentType<IconProps>',
    '> = {',
    ...entries,
    '};',
    '',
  ].join('\n');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const source = iconsTsx();
  if (process.argv.includes('--check')) {
    let current = '';
    try {
      current = readFileSync(target, 'utf8');
    } catch {
      // Missing counts as drift.
    }
    if (current !== source) {
      console.error(
        'src/generated/icons.tsx is out of date: run pnpm --filter @allotr/web icons',
      );
      process.exit(1);
    }
  } else {
    writeFileSync(target, source);
  }
}
