import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import {
  DEFAULT_PALETTE_THEME_ID,
  findPaletteTheme,
  ROLES,
  THEME_SCHEMES,
} from '@allotr/shared';
import {
  EASE_EXIT,
  FADE_MS,
  linearEasing,
  SPRING_TOKENS,
  SPRINGS,
} from '../src/lib/springs.ts';

// Writes src/generated/tokens.css: the default theme of each scheme as
// resolved roles, and the spring tokens as `linear()` easings (ADR 0016,
// ADR 0019). `--check` fails when the file differs from what would be
// written, so the stylesheet never drifts from the resolver or the springs.

const target = fileURLToPath(
  new URL('../src/generated/tokens.css', import.meta.url),
);

function roles(scheme: (typeof THEME_SCHEMES)[number]): string[] {
  const theme = findPaletteTheme(DEFAULT_PALETTE_THEME_ID[scheme], []);
  if (theme === undefined) throw new Error(`No default ${scheme} theme`);
  return [
    `  /* ${theme.name} */`,
    ...ROLES.map((role) => `  --${role}: ${theme.resolved.roles[role]};`),
    `  color-scheme: ${scheme};`,
  ];
}

const durations = SPRING_TOKENS.map((token) => `  --dur-${token}: 0ms;`);

export function tokensCss(): string {
  return [
    '/* Generated by scripts/generate-tokens.ts. Do not edit. */',
    '',
    ':root {',
    ...roles('light'),
    '}',
    '',
    ":root[data-theme='dark'] {",
    ...roles('dark'),
    '}',
    '',
    ':root {',
    ...SPRING_TOKENS.flatMap((token) => {
      const { easing, durationMs } = linearEasing(SPRINGS[token]);
      return [
        `  --ease-${token}: ${easing};`,
        `  --dur-${token}: ${String(durationMs)}ms;`,
      ];
    }),
    `  --ease-exit: ${EASE_EXIT.easing};`,
    `  --dur-exit: ${String(EASE_EXIT.ms)}ms;`,
    `  --dur-fade: ${String(FADE_MS)}ms;`,
    '}',
    '',
    '/* Reduced motion: springs stop; only the short crossfade stays. */',
    '@media (prefers-reduced-motion: reduce) {',
    "  :root:not([data-motion='full']) {",
    ...durations.map((line) => `  ${line}`),
    '    --dur-exit: 0ms;',
    '  }',
    '}',
    '',
    ":root[data-motion='reduced'],",
    ":root[data-motion='off'] {",
    ...durations,
    '  --dur-exit: 0ms;',
    '}',
    '',
    ":root[data-motion='off'] {",
    '  --dur-fade: 0ms;',
    '}',
    '',
  ].join('\n');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const css = tokensCss();
  if (process.argv.includes('--check')) {
    let current = '';
    try {
      current = readFileSync(target, 'utf8');
    } catch {
      // Missing counts as drift.
    }
    if (current !== css) {
      console.error(
        'src/generated/tokens.css is out of date: run pnpm --filter @allotr/web tokens',
      );
      process.exit(1);
    }
  } else {
    writeFileSync(target, css);
  }
}
