import type { CategoryIcon } from '@allotr/shared';

// Remix Icon 4.5.0 glyphs the web app uses (docs/ui.md §7). Names are the
// file names without `.svg`. Run `pnpm --filter @allotr/web icons` after
// editing.

/** Stored category icon key to Remix glyph. */
export const CATEGORY_ICON_MAP = {
  banknote: 'money-dollar-box-line',
  baby: 'parent-line',
  beer: 'beer-line',
  bike: 'riding-line',
  'book-open': 'book-open-line',
  briefcase: 'briefcase-4-line',
  bus: 'bus-line',
  car: 'car-line',
  'circle-dollar-sign': 'money-dollar-circle-line',
  coffee: 'cup-line',
  'credit-card': 'bank-card-line',
  dumbbell: 'run-line',
  film: 'film-line',
  fuel: 'gas-station-line',
  'gamepad-2': 'gamepad-line',
  gift: 'gift-line',
  'graduation-cap': 'graduation-cap-line',
  'hand-coins': 'hand-coin-line',
  'heart-pulse': 'heart-pulse-line',
  house: 'home-4-line',
  landmark: 'bank-line',
  laptop: 'macbook-line',
  lightbulb: 'lightbulb-flash-line',
  music: 'music-2-line',
  'paw-print': 'bear-smile-line',
  percent: 'percent-line',
  'piggy-bank': 'safe-2-line',
  pill: 'capsule-line',
  plane: 'plane-line',
  receipt: 'bill-line',
  repeat: 'repeat-line',
  scissors: 'scissors-cut-line',
  shirt: 't-shirt-line',
  'shopping-bag': 'shopping-bag-line',
  'shopping-basket': 'shopping-basket-line',
  smartphone: 'smartphone-line',
  sparkles: 'sparkling-line',
  tag: 'price-tag-3-line',
  ticket: 'ticket-line',
  'train-front': 'train-line',
  'tree-pine': 'tree-line',
  'trending-up': 'line-chart-line',
  umbrella: 'umbrella-line',
  utensils: 'restaurant-2-line',
  'utensils-crossed': 'restaurant-line',
  wallet: 'wallet-3-line',
  wifi: 'wifi-line',
  wrench: 'tools-line',
} as const satisfies Readonly<Record<CategoryIcon, string>>;

/** Interface icons: destinations, tile titles, actions, states. */
export const INTERFACE_ICONS = [
  'dashboard-3-line',
  'bank-line',
  'arrow-left-right-line',
  'pie-chart-2-line',
  'line-chart-line',
  'settings-3-line',
  'add-line',
  'close-line',
  'search-line',
  'filter-3-line',
  'arrow-down-s-line',
  'arrow-right-s-line',
  'arrow-up-s-line',
  'arrow-down-line',
  'arrow-up-line',
  'more-2-line',
  'check-line',
  'calendar-line',
  'time-line',
  'bill-line',
  'flag-line',
  'group-line',
  'scales-3-line',
  'error-warning-line',
  'information-line',
  'drag-move-line',
  'refresh-line',
  'wifi-off-line',
  'delete-bin-line',
  'edit-line',
  'scissors-cut-line',
  'history-line',
  'link',
  'sort-desc',
  'sort-asc',
  'layout-grid-line',
  'list-check',
  'play-circle-line',
  'shield-keyhole-line',
  'download-2-line',
  'upload-2-line',
  'palette-line',
  'keyboard-line',
  'user-line',
  'logout-box-line',
] as const;
