import type { CurrencyCode, LocalDate, Money, Rate } from '@allotr/shared';

// The append-only double-entry ledger (docs/domain.md "Accounts and
// double-entry"). Values are plain frozen data; build transactions with
// the functions in build.ts and reverse.ts, which check the invariants.

declare const brand: unique symbol;
type Brand<T, B extends string> = T & { readonly [brand]: B };

export type AccountId = Brand<string, 'AccountId'>;
export type TransactionId = Brand<string, 'TransactionId'>;
export type CategoryId = Brand<string, 'CategoryId'>;

// IDs are generated by the caller: core has no randomness.
export const accountId = (id: string) => id as AccountId;
export const transactionId = (id: string) => id as TransactionId;
export const categoryId = (id: string) => id as CategoryId;

export type BudgetGroup = 'on' | 'off';

export type UserAccountKind = 'asset' | 'liability' | 'receivable' | 'payable';

/**
 * Balancing accounts, one per user, role and currency. `receivables` and
 * `payables` hold what people owe the user and what the user owes them
 * (ADR 0024).
 */
export type SystemRole =
  'expenses' | 'income' | 'opening' | 'conversion' | 'receivables' | 'payables';

export type Account = Readonly<
  {
    id: AccountId;
    currency: CurrencyCode;
    archived: boolean;
  } & (
    | {
        kind: UserAccountKind;
        systemRole: null;
        /** The group at creation; later switches are transactions. */
        budgetGroup: BudgetGroup;
      }
    | {
        kind: 'expense' | 'income' | 'equity' | 'receivable' | 'payable';
        systemRole: SystemRole;
        budgetGroup: null;
      }
  )
>;

export type Posting = Readonly<{
  accountId: AccountId;
  amount: Money;
  /** Set on the balancing leg of an expense or income. */
  categoryId: CategoryId | null;
}>;

export type TransactionKind =
  | 'expense'
  | 'income'
  | 'transfer'
  | 'opening'
  | 'write_off'
  | 'budget_switch'
  | 'reversal';

export type BudgetSwitch = Readonly<{
  accountId: AccountId;
  budgetGroup: BudgetGroup;
}>;

export type Transaction = Readonly<{
  id: TransactionId;
  kind: TransactionKind;
  occurredOn: LocalDate;
  /** ISO 8601 UTC instant; orders entries made on the same date. */
  createdAt: string;
  /** Null for a split: each balancing posting then carries its own. */
  categoryId: CategoryId | null;
  note: string | null;
  postings: readonly Posting[];
  reversesId: TransactionId | null;
  /** Units received per unit sent, for cross-currency transfers. */
  impliedRate: Rate | null;
  budgetSwitch: BudgetSwitch | null;
}>;

/** Who, when and why for a new transaction. */
export type EntryMeta = Readonly<{
  id: TransactionId;
  occurredOn: LocalDate;
  createdAt: string;
  note?: string | null;
}>;
