/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Accounts {
  archived: Generated<number>;
  budget_group: string | null;
  created_at: string;
  currency: string;
  id: string;
  kind: string;
  name: string;
  system_role: string | null;
  updated_at: string;
  user_id: string;
}

export interface AuthAccounts {
  access_token: string | null;
  access_token_expires_at: string | null;
  account_id: string;
  created_at: string;
  id: string;
  id_token: string | null;
  password: string | null;
  provider_id: string;
  refresh_token: string | null;
  refresh_token_expires_at: string | null;
  scope: string | null;
  updated_at: string;
  user_id: string;
}

export interface BillPayments {
  bill_id: string;
  created_at: string;
  due_on: string;
  id: string;
  paid_on: string;
  recorded: Generated<number>;
  transaction_id: string | null;
  user_id: string;
}

export interface Bills {
  account_id: string;
  active: Generated<number>;
  amount_minor: number;
  category_id: string | null;
  created_at: string;
  currency: string;
  due_day: number;
  id: string;
  name: string;
  price_currency: string | null;
  price_minor: number | null;
  updated_at: string;
  user_id: string;
}

export interface BudgetAmounts {
  amount_minor: number;
  budget_id: string;
  created_at: string;
  currency: string;
  effective_on: string;
  id: string;
  user_id: string;
}

export interface Budgets {
  category_id: string | null;
  created_at: string;
  ended_on: string | null;
  id: string;
  kind: string;
  leftover: string;
  mode: string;
  name: string;
  started_on: string;
  tag_id: string | null;
  updated_at: string;
  user_id: string;
}

export interface Categories {
  created_at: string;
  default_account_id: string | null;
  id: string;
  is_paycheck: Generated<number>;
  kind: string;
  merged_into_id: string | null;
  name: string;
  parent_id: string | null;
  position: Generated<number>;
  updated_at: string;
  user_id: string;
}

export interface CoverOverrides {
  amount_minor: number;
  created_at: string;
  currency: string;
  id: string;
  position: number;
  source: string;
  transaction_id: string;
  user_id: string;
}

export interface FxRates {
  as_of: string;
  base: string;
  created_at: string;
  id: string;
  quote: string;
  rate: string;
  source: string;
  user_id: string;
}

export interface InstanceSettings {
  key: string;
  updated_at: string;
  value: string;
}

export interface Invites {
  created_at: string;
  created_by: string;
  expires_at: string;
  id: string;
  token_hash: string;
  used_at: string | null;
  used_by: string | null;
}

export interface PoolMoves {
  account_id: string;
  created_at: string;
  effective_on: string;
  id: string;
  pool_id: string;
  user_id: string;
}

export interface Pools {
  archived: Generated<number>;
  counts_toward_daily: number;
  created_at: string;
  default_for: string | null;
  id: string;
  kind: string;
  name: string;
  position: Generated<number>;
  updated_at: string;
  user_id: string;
}

export interface Postings {
  account_id: string;
  amount_minor: number;
  category_id: string | null;
  currency: string;
  id: string;
  position: number;
  transaction_id: string;
  user_id: string;
}

export interface Reconciliations {
  account_id: string;
  adjustment_transaction_id: string | null;
  computed_minor: number;
  created_at: string;
  currency: string;
  id: string;
  on_date: string;
  stated_minor: number;
  user_id: string;
}

export interface SchemaMigrations {
  applied_at: string;
  checksum: string;
  version: string;
}

export interface Sessions {
  created_at: string;
  expires_at: string;
  id: string;
  ip_address: string | null;
  token: string;
  updated_at: string;
  user_agent: string | null;
  user_id: string;
}

export interface SignInFailures {
  email: string;
  failed_count: number;
  locked_until: string | null;
  window_started_at: string;
}

export interface StarterCategories {
  is_paycheck: number;
  kind: string;
  name: string;
  parent_name: string | null;
  position: number;
}

export interface Tags {
  created_at: string;
  id: string;
  name: string;
  updated_at: string;
  user_id: string;
}

export interface Transactions {
  category_id: string | null;
  created_at: string;
  fx_rate_implied: string | null;
  id: string;
  idempotency_key: string | null;
  kind: string;
  note: string | null;
  occurred_on: string;
  reverses_id: string | null;
  source: string;
  switch_account_id: string | null;
  switch_budget_group: string | null;
  user_id: string;
}

export interface TransactionTags {
  tag_id: string;
  transaction_id: string;
  user_id: string;
}

export interface TwoFactors {
  backup_codes: string;
  failed_verification_count: Generated<number>;
  id: string;
  locked_until: string | null;
  secret: string;
  user_id: string;
  verified: number | null;
}

export interface Users {
  created_at: string;
  default_currency: Generated<string>;
  email: string;
  email_verified: Generated<number>;
  id: string;
  image: string | null;
  locale: Generated<string>;
  name: string;
  role: Generated<string>;
  two_factor_enabled: Generated<number>;
  tz: Generated<string>;
  updated_at: string;
}

export interface UserSettings {
  key: string;
  updated_at: string;
  user_id: string;
  value: string;
}

export interface Verifications {
  created_at: string;
  expires_at: string;
  id: string;
  identifier: string;
  updated_at: string;
  value: string;
}

export interface DB {
  accounts: Accounts;
  auth_accounts: AuthAccounts;
  bill_payments: BillPayments;
  bills: Bills;
  budget_amounts: BudgetAmounts;
  budgets: Budgets;
  categories: Categories;
  cover_overrides: CoverOverrides;
  fx_rates: FxRates;
  instance_settings: InstanceSettings;
  invites: Invites;
  pool_moves: PoolMoves;
  pools: Pools;
  postings: Postings;
  reconciliations: Reconciliations;
  schema_migrations: SchemaMigrations;
  sessions: Sessions;
  sign_in_failures: SignInFailures;
  starter_categories: StarterCategories;
  tags: Tags;
  transaction_tags: TransactionTags;
  transactions: Transactions;
  two_factors: TwoFactors;
  user_settings: UserSettings;
  users: Users;
  verifications: Verifications;
}
