/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface InstanceSettings {
  key: string;
  updated_at: string;
  value: string;
}

export interface SchemaMigrations {
  applied_at: string;
  checksum: string;
  version: string;
}

export interface DB {
  instance_settings: InstanceSettings;
  schema_migrations: SchemaMigrations;
}
