import {
  accountListSchema,
  accountSchema,
  appearanceBodySchema,
  appearanceSchema,
  archiveAccountBodySchema,
  archiveImpactSchema,
  billListSchema,
  billSchema,
  categoryListSchema,
  categorySchema,
  createCategoryBodySchema,
  cycleDayListSchema,
  accountHistorySchema,
  cycleDetailSchema,
  cycleListSchema,
  createInviteBodySchema,
  createRateBodySchema,
  createAccountBodySchema,
  createBillBodySchema,
  createBillPaymentBodySchema,
  createTransactionBodySchema,
  customThemeViewListSchema,
  customThemeViewSchema,
  deleteUserBodySchema,
  editedTransactionSchema,
  instanceSettingsPatchSchema,
  instanceSettingsSchema,
  inviteSchema,
  inviteStatusSchema,
  exchangeRateListSchema,
  exchangeRateSchema,
  ledgerSettingsSchema,
  onboardingStatusSchema,
  reconcileBodySchema,
  reconcileResultSchema,
  reverseTransactionBodySchema,
  sessionSchema,
  sessionUserSchema,
  setupSchema,
  signUpBodySchema,
  tagBodySchema,
  tagListSchema,
  tagSchema,
  themeBodySchema,
  todaySchema,
  transactionListSchema,
  transactionSchema,
  updateAccountBodySchema,
  updateBillBodySchema,
  updateCategoryBodySchema,
  updateLedgerSettingsBodySchema,
} from '@allotr/shared';
import { z } from 'zod';
import { endpoint } from './api.ts';

// Every server call the web app makes. Paths use the OpenAPI `{name}` form;
// endpoints.test.ts checks them against docs/openapi.json.

const signInBodySchema = z.object({ email: z.string(), password: z.string() });
const passwordBodySchema = z.object({ password: z.string() });

/** A Better Auth session as its list route returns it. */
export const authSessionSchema = z.object({
  id: z.string(),
  token: z.string(),
  userAgent: z.string().nullish(),
  ipAddress: z.string().nullish(),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
});
export type AuthSession = z.infer<typeof authSessionSchema>;

export const endpoints = {
  onboardingStatus: endpoint({
    method: 'GET',
    path: '/v1/onboarding',
    response: onboardingStatusSchema,
  }),
  createFirstAccount: endpoint({
    method: 'POST',
    path: '/v1/onboarding',
    body: signUpBodySchema,
    response: z.object({ user: sessionUserSchema }),
  }),
  session: endpoint({
    method: 'GET',
    path: '/v1/session',
    response: sessionSchema,
  }),
  signIn: endpoint({
    method: 'POST',
    path: '/v1/auth/sign-in/email',
    body: signInBodySchema,
    response: z.union([
      z.object({ twoFactorRedirect: z.literal(true) }),
      z.object({ user: z.object({ id: z.string() }) }),
    ]),
    openapi: false,
  }),
  verifyTotp: endpoint({
    method: 'POST',
    path: '/v1/auth/two-factor/verify-totp',
    body: z.object({ code: z.string() }),
    response: z.unknown(),
    openapi: false,
  }),
  verifyBackupCode: endpoint({
    method: 'POST',
    path: '/v1/auth/two-factor/verify-backup-code',
    body: z.object({ code: z.string() }),
    response: z.unknown(),
    openapi: false,
  }),
  enableTwoFactor: endpoint({
    method: 'POST',
    path: '/v1/auth/two-factor/enable',
    body: passwordBodySchema,
    response: z.object({
      totpURI: z.string(),
      backupCodes: z.array(z.string()),
    }),
    openapi: false,
  }),
  disableTwoFactor: endpoint({
    method: 'POST',
    path: '/v1/auth/two-factor/disable',
    body: passwordBodySchema,
    response: z.unknown(),
    openapi: false,
  }),
  currentAuthSession: endpoint({
    method: 'GET',
    path: '/v1/auth/get-session',
    response: z.object({ session: z.object({ token: z.string() }) }).nullable(),
    openapi: false,
  }),
  authSessions: endpoint({
    method: 'GET',
    path: '/v1/auth/list-sessions',
    response: z.array(authSessionSchema),
    openapi: false,
  }),
  revokeSession: endpoint({
    method: 'POST',
    path: '/v1/auth/revoke-session',
    body: z.object({ token: z.string() }),
    response: z.unknown(),
    openapi: false,
  }),
  revokeOtherSessions: endpoint({
    method: 'POST',
    path: '/v1/auth/revoke-other-sessions',
    body: z.object({}),
    response: z.unknown(),
    openapi: false,
  }),
  signOut: endpoint({
    method: 'POST',
    path: '/v1/auth/sign-out',
    body: z.object({}),
    response: z.unknown(),
    openapi: false,
  }),
  deleteUser: endpoint({
    method: 'POST',
    path: '/v1/user/delete',
    body: deleteUserBodySchema,
    response: z.unknown(),
  }),
  instanceSettings: endpoint({
    method: 'GET',
    path: '/v1/admin/settings',
    response: instanceSettingsSchema,
  }),
  updateInstanceSettings: endpoint({
    method: 'PATCH',
    path: '/v1/admin/settings',
    body: instanceSettingsPatchSchema,
    response: instanceSettingsSchema,
  }),
  createInvite: endpoint({
    method: 'POST',
    path: '/v1/invites',
    body: createInviteBodySchema,
    response: inviteSchema,
  }),
  inviteStatus: endpoint({
    method: 'GET',
    path: '/v1/invites/{token}',
    response: inviteStatusSchema,
  }),
  acceptInvite: endpoint({
    method: 'POST',
    path: '/v1/invites/{token}/accept',
    body: signUpBodySchema,
    response: z.object({ user: sessionUserSchema }),
  }),
  appearance: endpoint({
    method: 'GET',
    path: '/v1/settings/appearance',
    response: appearanceSchema,
  }),
  saveAppearance: endpoint({
    method: 'PUT',
    path: '/v1/settings/appearance',
    body: appearanceBodySchema,
    response: appearanceSchema,
  }),
  themes: endpoint({
    method: 'GET',
    path: '/v1/settings/themes',
    response: customThemeViewListSchema,
  }),
  createTheme: endpoint({
    method: 'POST',
    path: '/v1/settings/themes',
    body: themeBodySchema,
    response: customThemeViewSchema,
  }),
  updateTheme: endpoint({
    method: 'PUT',
    path: '/v1/settings/themes/{id}',
    body: themeBodySchema,
    response: customThemeViewSchema,
  }),
  deleteTheme: endpoint({
    method: 'DELETE',
    path: '/v1/settings/themes/{id}',
    response: z.unknown(),
  }),
  setup: endpoint({
    method: 'GET',
    path: '/v1/settings/setup',
    response: setupSchema,
  }),
  saveSetup: endpoint({
    method: 'PUT',
    path: '/v1/settings/setup',
    body: setupSchema,
    response: setupSchema,
  }),
  accounts: endpoint({
    method: 'GET',
    path: '/v1/accounts',
    response: accountListSchema,
  }),
  createAccount: endpoint({
    method: 'POST',
    path: '/v1/accounts',
    body: createAccountBodySchema,
    response: accountSchema,
  }),
  updateAccount: endpoint({
    method: 'PATCH',
    path: '/v1/accounts/{id}',
    body: updateAccountBodySchema,
    response: accountSchema,
  }),
  archiveAccount: endpoint({
    method: 'POST',
    path: '/v1/accounts/{id}/archive',
    body: archiveAccountBodySchema,
    response: accountSchema,
  }),
  archiveImpact: endpoint({
    method: 'GET',
    path: '/v1/accounts/{id}/archive-impact',
    response: archiveImpactSchema,
  }),
  reconcileAccount: endpoint({
    method: 'POST',
    path: '/v1/accounts/{id}/reconcile',
    body: reconcileBodySchema,
    response: reconcileResultSchema,
  }),
  categories: endpoint({
    method: 'GET',
    path: '/v1/categories',
    response: categoryListSchema,
  }),
  createCategory: endpoint({
    method: 'POST',
    path: '/v1/categories',
    body: createCategoryBodySchema,
    response: categorySchema,
  }),
  updateCategory: endpoint({
    method: 'PATCH',
    path: '/v1/categories/{id}',
    body: updateCategoryBodySchema,
    response: categorySchema,
  }),
  deleteCategory: endpoint({
    method: 'DELETE',
    path: '/v1/categories/{id}',
    response: z.unknown(),
  }),
  tags: endpoint({
    method: 'GET',
    path: '/v1/tags',
    response: tagListSchema,
  }),
  createTag: endpoint({
    method: 'POST',
    path: '/v1/tags',
    body: tagBodySchema,
    response: tagSchema,
  }),
  renameTag: endpoint({
    method: 'PATCH',
    path: '/v1/tags/{id}',
    body: tagBodySchema,
    response: tagSchema,
  }),
  ledgerSettings: endpoint({
    method: 'GET',
    path: '/v1/settings/ledger',
    response: ledgerSettingsSchema,
  }),
  updateLedgerSettings: endpoint({
    method: 'PATCH',
    path: '/v1/settings/ledger',
    body: updateLedgerSettingsBodySchema,
    response: ledgerSettingsSchema,
  }),
  bills: endpoint({
    method: 'GET',
    path: '/v1/bills',
    response: billListSchema,
  }),
  createBill: endpoint({
    method: 'POST',
    path: '/v1/bills',
    body: createBillBodySchema,
    response: billSchema,
  }),
  updateBill: endpoint({
    method: 'PATCH',
    path: '/v1/bills/{id}',
    body: updateBillBodySchema,
    response: billSchema,
  }),
  deleteBill: endpoint({
    method: 'DELETE',
    path: '/v1/bills/{id}',
    response: z.unknown(),
  }),
  payBill: endpoint({
    method: 'POST',
    path: '/v1/bills/{id}/payments',
    body: createBillPaymentBodySchema,
    response: billSchema,
  }),
  unpayBill: endpoint({
    method: 'DELETE',
    path: '/v1/bills/{id}/payments/{dueOn}',
    response: billSchema,
  }),
  rates: endpoint({
    method: 'GET',
    path: '/v1/rates',
    response: exchangeRateListSchema,
  }),
  createRate: endpoint({
    method: 'POST',
    path: '/v1/rates',
    body: createRateBodySchema,
    response: exchangeRateSchema,
  }),
  deleteRate: endpoint({
    method: 'DELETE',
    path: '/v1/rates/{id}',
    response: z.unknown(),
  }),
  today: endpoint({
    method: 'GET',
    path: '/v1/today',
    response: todaySchema,
  }),
  cycles: endpoint({
    method: 'GET',
    path: '/v1/cycles',
    response: cycleListSchema,
  }),
  cycle: endpoint({
    method: 'GET',
    path: '/v1/cycles/{openedOn}',
    response: cycleDetailSchema,
  }),
  accountHistory: endpoint({
    method: 'GET',
    path: '/v1/accounts/{id}/history',
    response: accountHistorySchema,
  }),
  cycleDays: endpoint({
    method: 'GET',
    path: '/v1/cycles/{openedOn}/days',
    response: cycleDayListSchema,
  }),
  transactions: endpoint({
    method: 'GET',
    path: '/v1/transactions',
    response: transactionListSchema,
  }),
  createTransaction: endpoint({
    method: 'POST',
    path: '/v1/transactions',
    body: createTransactionBodySchema,
    response: transactionSchema,
  }),
  transaction: endpoint({
    method: 'GET',
    path: '/v1/transactions/{id}',
    response: transactionSchema,
  }),
  editTransaction: endpoint({
    method: 'POST',
    path: '/v1/transactions/{id}/edit',
    body: createTransactionBodySchema,
    response: editedTransactionSchema,
  }),
  reverseTransaction: endpoint({
    method: 'POST',
    path: '/v1/transactions/{id}/reverse',
    body: reverseTransactionBodySchema,
    response: transactionSchema,
  }),
};
